// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRBNeUwID2o8BR0nXXGKjWplXC6Vj7ISQ',
    appId: '1:688584279084:android:6498e044a8dd5fd1993d89',
    messagingSenderId: '688584279084',
    projectId: 'claimizer-a73e7',
    storageBucket: 'claimizer-a73e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQvrkXQ-ZPWPhBlf-b9ciWvBvkq5QmJp0',
    appId: '1:688584279084:ios:80fd7a2df2c2243c993d89',
    messagingSenderId: '688584279084',
    projectId: 'claimizer-a73e7',
    storageBucket: 'claimizer-a73e7.firebasestorage.app',
    androidClientId: '688584279084-0s36tet8ou9lf6ou5hkvo5lu92920a76.apps.googleusercontent.com',
    iosClientId: '688584279084-qv5h79oj86tm2oace5ir95gsfjrlg6rt.apps.googleusercontent.com',
    iosBundleId: 'com.app.claimizer',
  );

}